name: backend-ci

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: calculator-server
        run: |
          python -m pip install --upgrade pip
          pip install "fastapi>=0.110" "uvicorn[standard]>=0.27" "asteval>=0.9" "pytest>=7" "httpx>=0.27"

      - name: Run tests
        working-directory: calculator-server
        run: pytest -q


